baseURL = "https://www.garrettsiegel.com/"
languageCode = 'en-us'
title = 'Garrett Siegel | Frontend Developer and Graphic Designer'

[params]
name = 'Garrett Siegel'
email = 'garrett@submurgedcreative.com'